"""
Synthetic Transformer with Planted Features

Constructs a known, controllable transformer-like model where:
- N true feature directions are planted by construction
- Each feature has a known computation path across layers
- Ground truth is fully accessible for evaluation

Key design decisions:
- Features stored in superposition via near-orthogonal directions
- Computation between layers is a known linear+nonlinear map
- Data generated by randomly activating k-sparse subsets of features

This is used to PROVE CCJFR works before touching real models.
"""

import torch
import torch.nn as nn
import numpy as np
from dataclasses import dataclass
from typing import Optional


@dataclass
class SyntheticConfig:
    n_features: int = 100       # True planted features
    d_model: int = 256          # Residual stream dimension
    n_layers: int = 3           # Number of layers
    sparsity_k: int = 5         # Features active per input (k-sparse)
    n_samples: int = 50_000     # Training data size
    noise_std: float = 0.01     # Observation noise
    seed: int = 42


class SyntheticTransformer(nn.Module):
    """
    A synthetic transformer with fully known, planted features.

    The model computes:
        h_0 = E · z_0               # Embed sparse features
        h_l = h_{l-1} + T_l(h_{l-1}) for l = 1, ..., L

    Where T_l is known (constructed by us), so we always know:
        - What the true features are at each layer
        - Exactly how features transform between layers
    """

    def __init__(self, config: SyntheticConfig):
        super().__init__()
        self.config = config
        torch.manual_seed(config.seed)

        C, D, N = config.n_features, config.d_model, config.n_layers

        # --- Plant true feature directions ---
        # Random near-orthogonal directions in d_model space
        # Shape: [n_features, d_model]
        raw = torch.randn(C, D)
        # Orthogonalize (at least partially) via QR on a subset
        if C <= D:
            Q, _ = torch.linalg.qr(raw.T)  # [D, C]
            self.feature_directions = Q.T   # [C, D] — orthonormal if C <= D
        else:
            # C > D: can't be fully orthogonal, use normalized random
            self.feature_directions = nn.functional.normalize(raw, dim=1)

        # Store as buffer (not trainable — this is ground truth)
        self.register_buffer('true_features', self.feature_directions)  # [C, D]

        # --- Planting at layer 0 (embedding analogue) ---
        # Layer 0 encodes: h_0 = true_features.T @ z_0
        # So the "embedding matrix" IS the true feature directions
        self.register_buffer('embed_matrix', self.feature_directions.T)  # [D, C]

        # --- Per-layer computation maps ---
        # T_l is a known nonlinear map: h_l = h_{l-1} + W_l * gelu(U_l * h_{l-1})
        # This mimics the structure of transformer MLP layers
        # We store the weights so we can compute the Jacobian exactly
        self.layer_weights_in = nn.ParameterList([
            nn.Parameter(torch.randn(D // 2, D) * 0.1, requires_grad=False)
            for _ in range(N)
        ])
        self.layer_weights_out = nn.ParameterList([
            nn.Parameter(torch.randn(D, D // 2) * 0.1, requires_grad=False)
            for _ in range(N)
        ])

        # --- Unembedding analogue (last layer → feature space) ---
        # The unembedding matrix is the true features transposed
        # So logit of feature f = true_features[f] · h_L
        self.register_buffer('unembed_matrix', self.feature_directions)  # [C, D]

        # Pre-compute true feature activations per layer
        # feature_at_layer[l] stores how much each true feature
        # survives/transforms at layer l (for evaluation)
        self._compute_layer_feature_maps()

    def _compute_layer_feature_maps(self):
        """
        For each layer l, compute what each true feature at layer 0
        maps to at layer l. Used for ground truth evaluation.
        """
        with torch.no_grad():
            # Start: identity (feature i at layer 0 = feature i)
            # We track the directions in h-space
            feature_dirs = self.true_features.clone()  # [C, D]

            self.layer_feature_dirs = [feature_dirs.clone()]

            for l in range(self.config.n_layers):
                W_in = self.layer_weights_in[l]   # [D//2, D]
                W_out = self.layer_weights_out[l]  # [D, D//2]

                # Compute how each feature direction transforms through T_l
                # T_l(h) = W_out @ gelu(W_in @ h)
                # Linearized (Jacobian) at h≈0: T_l ≈ W_out @ (0.5 * W_in)
                # For small weights, this is a reasonable approximation
                J_l = W_out @ (0.5 * W_in)  # [D, D] — Jacobian at h=0

                # Update feature directions through this layer
                # h_l = h_{l-1} + T_l(h_{l-1}) ≈ (I + J_l) @ h_{l-1}
                new_dirs = feature_dirs + (feature_dirs @ J_l.T)
                new_dirs = nn.functional.normalize(new_dirs, dim=1)

                feature_dirs = new_dirs
                self.layer_feature_dirs.append(feature_dirs.clone())

    def forward(self, z: torch.Tensor) -> list[torch.Tensor]:
        """
        Forward pass given sparse feature activations z.

        Args:
            z: [batch, n_features] sparse activations (k-sparse)

        Returns:
            activations: list of [batch, d_model] — one per layer (including h_0)
        """
        # Embed: h_0 = embed_matrix @ z.T => shape [batch, d_model]
        h = z @ self.embed_matrix.T  # [batch, d_model]
        activations = [h.clone()]

        for l in range(self.config.n_layers):
            W_in = self.layer_weights_in[l]
            W_out = self.layer_weights_out[l]
            # MLP-like: h = h + W_out @ gelu(W_in @ h.T)
            h = h + torch.nn.functional.gelu(h @ W_in.T) @ W_out.T
            activations.append(h.clone())

        return activations

    def generate_data(
        self,
        n_samples: Optional[int] = None,
        seed: Optional[int] = None
    ) -> tuple[torch.Tensor, list[torch.Tensor]]:
        """
        Generate k-sparse synthetic data.

        Returns:
            z_true: [n_samples, n_features] ground truth sparse codes
            activations: list of [n_samples, d_model] — one per layer
        """
        if n_samples is None:
            n_samples = self.config.n_samples
        if seed is not None:
            torch.manual_seed(seed)

        C, k = self.config.n_features, self.config.sparsity_k

        # Generate k-sparse activations (Bernoulli * Uniform positive)
        mask = torch.zeros(n_samples, C)
        for i in range(n_samples):
            idx = torch.randperm(C)[:k]
            mask[i, idx] = torch.rand(k).abs() + 0.5  # Uniform in [0.5, 1.5]

        z_true = mask  # [n_samples, n_features]

        with torch.no_grad():
            activations = self.forward(z_true)

        # Add small noise to make it realistic
        if self.config.noise_std > 0:
            activations = [
                h + torch.randn_like(h) * self.config.noise_std
                for h in activations
            ]

        return z_true, activations


def get_true_features_at_layer(model: SyntheticTransformer, layer: int) -> torch.Tensor:
    """Return the ground truth feature directions at a given layer. [C, D]"""
    return model.layer_feature_dirs[layer]
